---
# setup default page

- name: Ensure default template exists
  copy:
    src: www/
    dest: "{{www_dir}}/default/"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0644
    directory_mode: 0755
    force: false
  tags: ['nginx']

- name: Ensure default page nginx template exists
  template:
    src: default.j2
    dest: "{{vhosts_dir}}/default.conf"
    owner: root
    group: root
    mode: 0644
    force: false
  notify: restart nginx
  tags: ['nginx']
