---
# setup a default page

- name: Ensure default page directory exists
  file:
    path: /srv/www/default
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755
    state: directory
  tags: ['nginx']
- name: Ensure default page exists
  template:
    src: index.j2
    dest: "{{www_dir}}/default/index.html"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755
    force: false
  tags: ['nginx']
- name: Ensure default page nginx template exists
  template:
    src: default-www.j2
    dest: "{{vhosts_dir}}/default-www.conf"
    owner: root
    group: root
    mode: 0644
    force: false
  notify: restart nginx
  tags: ['nginx']
