---
# Configure firewall

- name: Ensure http port is open
  firewalld:
    zone: "{{firewall_zone}}"
    service: http
    permanent: true
    state: enabled
  notify: reload firewalld
  tags: ['nginx', 'firewall']
  when: open_http == true

- name: Ensure https port is open
  firewalld:
    zone: "{{firewall_zone}}"
    service: https
    permanent: true
    state: enabled
  notify: reload firewalld
  tags: ['nginx', 'firewall']
  when: open_https == true
