---
# Install and configure nginx

- name: Ensure nginx is installed
  package:
    name: "{{ packages }}"
    state: present
  tags: ['nginx']

- name: Ensure nginx service is enabled
  systemd:
    name: "{{ nginx_service }}"
    state: started
    enabled: true
  tags: ['nginx', 'systemd']
