FROM registry.opensuse.org/opensuse/leap:15.5

# Install systemd and development tools, clear cache
RUN zypper in -y systemd systemd-sysvinit python311 curl && rm -rf /var/cache/*

# Start container with systemd
ENTRYPOINT ["/usr/sbin/init"]
