---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: leap15_2
    image: grisu48/leap-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
  - name: buster
    image: grisu48/buster-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: true
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      leap15_2:
        vhosts_dir: "/etc/nginx/vhosts.d"
        nginxuser: nginx
        nginxgroup: nginx
        deploy_nginx_config: true
      buster:
        vhosts_dir: "/etc/nginx/sites-enabled"
        nginxuser: www-data
        nginxgroup: www-data
        deploy_nginx_config: false
verifier:
  name: testinfra
  lint:
    name: flake8
lint: |
  set -e
  yamllint .
