---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: leap15_4
    image: registry.opensuse.org/opensuse/leap:15.4
    dockerfile: Dockerfile.leap15_4
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    privileged: true
    cgroupns: host
    tmpfs:
      - /run
      - /tmp
  - name: bullseye
    image: docker.io/debian:bullseye
    dockerfile: Dockerfile.bullseye
    command: ${MOLECULE_DOCKER_COMMAND:-"/sbin/init"}
    privileged: true
    cgroupns: host
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      leap15_4:
        vhosts_dir: "/etc/nginx/vhosts.d"
        deploy_nginx_config: true
      bullseye:
        vhosts_dir: "/etc/nginx/sites-enabled"
        deploy_nginx_config: false
verifier:
  name: testinfra
