---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: leap15_5
    image: registry.opensuse.org/opensuse/leap:15.5
    dockerfile: Containerfile.leap15_5
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    systemd: true
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
  - name: leap15_6
    image: registry.opensuse.org/opensuse/leap:15.6
    dockerfile: Containerfile.leap15_6
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/sbin/init"}
    systemd: true
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
  - name: bookworm
    image: docker.io/debian:bookworm
    dockerfile: Containerfile.bookworm
    command: ${MOLECULE_DOCKER_COMMAND:-"/sbin/init"}
    systemd: true
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
provisioner:
  name: ansible
  inventory:
    host_vars:
      leap15_5:
        vhosts_dir: "/etc/nginx/vhosts.d"
        deploy_nginx_config: true
        ansible_python_interpreter: "/usr/bin/python3.11"
      leap15_6:
        vhosts_dir: "/etc/nginx/vhosts.d"
        deploy_nginx_config: true
        ansible_python_interpreter: "/usr/bin/python3.11"
      bullseye:
        vhosts_dir: "/etc/nginx/sites-enabled"
        deploy_nginx_config: false
      bookworm:
        vhosts_dir: "/etc/nginx/sites-enabled"
        deploy_nginx_config: false
verifier:
  name: testinfra
